name: motion_v2
description: A fancy widget that applies a gyroscope or hover based motion effect to its child.
version: 1.3.2+1
homepage: https://mohesu.com
repository: https://github.com/rvndsngwn/motion
issue_tracker: https://github.com/rvndsngwn/motion/issues?q=is%3Aissue+is%3Aopen

flutter:
  plugin:
    platforms:
      android:
        package: me.cendre.motion.plugin
        pluginClass: MotionPlugin
      ios:
        pluginClass: MTMotionPlugin
      web:
        default_package: motion_web

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  motion_web: ^1.3.3
  motion_platform_interface: ^1.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
