name: motion_web
description: The web implementation for the Motion plugin.
version: 1.3.3
homepage: https://cendre.me
repository: https://github.com/mrcendre/motion
issue_tracker: https://github.com/mrcendre/motion/issues?q=is%3Aissue+is%3Aopen

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: motion
    platforms:
      web:
        pluginClass: WebMotion
        fileName: motion_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  motion_platform_interface: ^1.3.3
  js: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
